# sonar-project.properties
sonar.projectKey=rsschool-devops-course-tasks
sonar.organization=oprokhorov
sonar.host.url=https://sonarcloud.io

sonar.sources=flask_app
sonar.language=py

# Exclude common non-source directories
sonar.exclusions=tests/**,venv/**,**/__pycache__/**,*.pyc,site-packages/**,lib/**,bin/**,include/**,*.egg-info/**
