# sonar-project.properties
sonar.projectKey=rsschool-devops-course-tasks
sonar.organization=oprokhorov
sonar.host.url=https://sonarcloud.io

sonar.sources=flask_app
sonar.language=py
sonar.inclusions=flask_app/**/*.py
sonar.exclusions=flask_app/venv/**,flask_app/**/venv/**,flask_app/**/__pycache__/**,flask_app/**/*.pyc,flask_app/site-packages/**,flask_app/lib/**,flask_app/bin/**,flask_app/include/**,flask_app/*.egg-info/**,tests/**,**/build-wrapper-dump.json

# Only enable Python analyzer
sonar.coverage.exclusions=**
sonar.excludedLanguages=js,css,html,xml,java,kotlin,go,cpp,c,cs,php,swift,scala,ruby,typescript
