pipeline {
    agent {
        kubernetes {
            yaml """
                apiVersion: v1
                kind: Pod
                spec:
                  containers:

                  - name: python
                    image: python:3.9
                    command:
                    - cat
                    tty: true

                  - name: docker
                    image: docker:20.10.16-dind
                    securityContext:
                      privileged: true
                    env:
                    - name: DOCKER_TLS_CERTDIR
                      value: "" # Disables TLS for Docker in Docker

                  - name: helm
                    image: alpine/helm:latest
                    command:
                    - cat
                    tty: true
            """
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'task_6', url: 'https://github.com/oprokhorov/rsschool-devops-course-tasks.git'
            }
        }

        stage('Build and Unit test') {
            steps {
                container('python') {
                    sh '''
                        cd flask_app/
                        python -m venv ../venv
                        . ../venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                        python -m unittest test_main.py
                    '''
                }
            }
        }

        stage('SonarQube scan') {
            steps {
                container('python') {
                    withCredentials([string(credentialsId: 'sonarcloud-token', variable: 'SONAR_TOKEN')]) {
                        sh '''
                            pip install pysonar
                            pysonar -Dsonar.token=$SONAR_TOKEN
                        '''
                        // Other parameters are read from sonar-project.properties in repo root
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                container('docker') {
                    script {
                        env.IMAGE_NAME = "oprokhorov/flask-hello"
                        env.IMAGE_TAG = "${BUILD_NUMBER}"

                        sh """
                            cd flask_app/
                            docker build -t ${env.IMAGE_NAME}:${env.IMAGE_TAG} -t ${env.IMAGE_NAME}:latest .
                        """
                    }
                }
            }
        }

        stage('Docker Push') {
            steps {
                container('docker') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh """
                            echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                            docker push oprokhorov/flask-hello:${BUILD_NUMBER}
                            docker push oprokhorov/flask-hello:latest
                            docker logout
                        """
                    }
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                container('helm') {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                            helm upgrade --install flask-hello ./flask_app_helm \
                                --set image.repository=oprokhorov/flask-hello \
                                --set image.tag=${BUILD_NUMBER} \
                                --namespace flask-hello \
                                --create-namespace \
                                --values ./flask_app_helm/values.yaml \
                                --wait
                        '''
                    }
                }
            }
        }

        // check if deployment is successful

        // notify

    }
}