name: Terraform CI/CD

on:
  push:
    branches:
    - main
    - task_1
  pull_request:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::824525457054:role/GithubActionsRole
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - run: terraform init
      - run: terraform fmt -check -recursive

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-check
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::824525457054:role/GithubActionsRole
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - run: terraform init
      - run: terraform plan -out=tfplan
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
          retention-days: 1

  terraform-apply:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only on push to main
    needs: [terraform-check, terraform-plan]
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::824525457054:role/GithubActionsRole
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/
      - run: terraform init
      - run: terraform apply tfplan
